name: Label issues when fixed on other branch
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Label Fixed Issues
      uses: gh-bot/fix-labeler@master
