name: Label issues when fixed on other branch
on: push

jobs:
  build:
    name: Label Fixed Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gh-bot/fix-labeler@master
